language: node_js
node_js:
- '8'
branchs:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_707fe97a17b5_key -iv $encrypted_707fe97a17b5_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
